unstable_features = true
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
enum_discrim_align_threshold = 20
fn_args_layout = "Tall"
fn_single_line = true
