name: Build

on:
  push:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: rui314/setup-mold@v1
    
    - uses: egor-tensin/setup-clang@v1
      with:
        version: latest
        platform: x64
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
